import logging
from brain.llm_client import llm_client


class FixValidator:
    """🛡️ The Quality Assurance Engineer.

    Uses Gemini to rigorously test and audit code generated by DeepSeek
    before letting it break the production loop.
    """

    def __init__(self):
        self.logger = logging.getLogger("FixValidator")

    async def validate_fix(
        self, file_path: str, proposed_code: str, original_error: str
    ) -> dict:
        """Asks Gemini to audit DeepSeek's code.

        Returns a dict: {"valid": True/False, "reason": "...",
        "suggested_tweaks": "..."}
        """
        self.logger.info(
            f"🔍 Sending proposed fix for {file_path} to Gemini for auditing..."
        )

        prompt = f"""
        You are the strict code critic and auditor for a self-healing AI OS.
        Another AI has generated code to fix an error, and you must review it before it goes live.

        Original Error: {original_error}

        PROPOSED CODE FOR {file_path}:
        ```python
        {proposed_code}
        ```

        CRITICAL INSTRUCTION:
        Your response must be strictly in valid JSON format. Do not use any markdown code blocks or text outside the JSON.
        Format required:
        {{
            "valid": true or false,
            "reason": "Detailed explanation of why it passed or failed",
            "suggested_tweaks": "If it failed, provide instructions on what to fix"
        }}
        """
        try:
            # Calls the critique method on your upgraded llm_client
            result = await llm_client.critique(prompt, use_json=True)
            return result

        except Exception as e:
            self.logger.error(f"Failed to get Gemini validation: {e}")
            return {
                "valid": False,
                "reason": f"Validator exception: {e}",
                "suggested_tweaks": "Check system logs.",
            }


# Global instance
fix_validator = FixValidator()